Changed two Typos in the german translation
moonlight-stream/moonlight-qt pull request #547
Opened 2021-03-17 19:27 UTC by DreiMusketiere

2021-03-20 12:25 UTC, reloxx13 commented
i made a pr with the compiled files, but did not get accepted now.   
https://github.com/DreiMusketiere/moonlight-qt/pull/1

2021-03-20 12:35 UTC, reloxx13 requested changes
Thank you for the corrections.

2021-03-20 12:35 UTC, reloxx13 commented on app/languages/qml_de.ts
> +        <translation>Solange eine vorherige Session auf dem Host läuft, kannst du nicht Pairen. Beende alle laufenden Apps oder starte den Host neu. Dann probiere das pairen nochmal.</translation>
"Pairen" has to be small (verb)

2021-03-20 12:35 UTC, reloxx13 commented on app/languages/qml_de.ts
> +        <translation>Nicht unterstützte FPS Optionenen können Stottern verursachen.</translation>
"Optionenen" one -en too much

2021-03-20 12:35 UTC, reloxx13 commented on app/languages/qml_de.ts
> +        <translation>Automatisch (Empfohlen)</translation>
this is not a new sentences, it should be small. but i think big is "ok" in this case.

2021-03-20 23:34 UTC, reloxx13 commented on app/languages/qml_de.ts
> +        <translation>Tritt unserer Discord Community bei</translation>
The community is not only on discord

2021-03-20 23:36 UTC, reloxx13 commented
I corrected everything from this PR in weblate   
https://hosted.weblate.org/projects/moonlight/moonlight-qt/de/

2021-03-22 22:57 UTC, SupervisedThinking commented on app/languages/qml_de.ts
> +        <translation>Solange eine vorherige Session auf dem Host läuft, kannst du nicht Pairen. Beende alle laufenden Apps oder starte den Host neu. Dann probiere das pairen nochmal.</translation>
> kannst du nicht pairen

>Dann probiere das Pairen nochmal

2021-03-25 14:38 UTC, cgutman commented
@DreiMusketiere can you verify that the changes I've pulled in through Weblate have addressed your concerns?

2021-03-25 14:54 UTC, DreiMusketiere commented
I don't see any Problem yet. If I find one, I will inform you.

2021-04-05 01:47 UTC, cgutman commented
Closing this. You can use Weblate to adjust translations further.

2021-04-05 01:47 UTC, closed without merging